-- =====================================================
-- SCRIPT DE CREACIÓN DE TABLAS Y SECUENCIAS PARA MM_MEET
-- =====================================================

-- Crear secuencia para ID_MEET
CREATE SEQUENCE SEQ_MM_MEET
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Crear tabla principal de reuniones
CREATE TABLE MM_MEET (
    ID_MEET NUMBER PRIMARY KEY,
    TITULO VARCHAR2(500) NOT NULL,
    DESCRIPCION VARCHAR2(1000),
    FECHA_INICIO DATE NOT NULL,
    HORA_INICIO DATE,
    FECHA_FIN DATE,
    HORA_FIN DATE,
    TOKEN_QR VARCHAR2(10),
    ID_SALA NUMBER NOT NULL,
    ID_PRIORIDAD NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    ID_TIPO_MEET NUMBER NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,
    FECHA_MODIFICACION DATE DEFAULT SYSDATE
);

-- Crear tabla de salas
CREATE TABLE MM_SALA (
    ID_SALA NUMBER PRIMARY KEY,
    NOMBRE_SALA VARCHAR2(100) NOT NULL,
    NIVEL NUMBER DEFAULT 1,
    HABILITADA CHAR(1) DEFAULT '1',
    FECHA_CREACION DATE DEFAULT SYSDATE
);

-- Crear tabla de prioridades
CREATE TABLE MM_PRIORIDAD (
    ID_PRIORIDAD NUMBER PRIMARY KEY,
    NOMBRE_PRIORIDAD VARCHAR2(50) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE
);

-- Crear tabla de estados de formulario
CREATE TABLE MM_ESTADO_FORMULARIO (
    ID_ESTADO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE
);

-- Crear tabla de tipos de reunión
CREATE TABLE MM_TIPO_MEET (
    ID_TIPO_MEET NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE
);

-- Crear secuencias para las tablas de catálogo
CREATE SEQUENCE SEQ_MM_SALA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MM_PRIORIDAD
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MM_ESTADO_FORMULARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MM_TIPO_MEET
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Insertar datos de ejemplo para catálogos
INSERT INTO MM_SALA (ID_SALA, NOMBRE_SALA, NIVEL, HABILITADA) VALUES (SEQ_MM_SALA.NEXTVAL, 'Sala de Juntas 1', 1, '1');
INSERT INTO MM_SALA (ID_SALA, NOMBRE_SALA, NIVEL, HABILITADA) VALUES (SEQ_MM_SALA.NEXTVAL, 'Sala de Juntas 2', 1, '1');
INSERT INTO MM_SALA (ID_SALA, NOMBRE_SALA, NIVEL, HABILITADA) VALUES (SEQ_MM_SALA.NEXTVAL, 'Sala de Conferencias', 2, '1');
INSERT INTO MM_SALA (ID_SALA, NOMBRE_SALA, NIVEL, HABILITADA) VALUES (SEQ_MM_SALA.NEXTVAL, 'Auditorio Principal', 3, '1');

INSERT INTO MM_PRIORIDAD (ID_PRIORIDAD, NOMBRE_PRIORIDAD) VALUES (SEQ_MM_PRIORIDAD.NEXTVAL, 'Baja');
INSERT INTO MM_PRIORIDAD (ID_PRIORIDAD, NOMBRE_PRIORIDAD) VALUES (SEQ_MM_PRIORIDAD.NEXTVAL, 'Media');
INSERT INTO MM_PRIORIDAD (ID_PRIORIDAD, NOMBRE_PRIORIDAD) VALUES (SEQ_MM_PRIORIDAD.NEXTVAL, 'Alta');
INSERT INTO MM_PRIORIDAD (ID_PRIORIDAD, NOMBRE_PRIORIDAD) VALUES (SEQ_MM_PRIORIDAD.NEXTVAL, 'Crítica');

INSERT INTO MM_ESTADO_FORMULARIO (ID_ESTADO, NOMBRE) VALUES (SEQ_MM_ESTADO_FORMULARIO.NEXTVAL, 'Pendiente');
INSERT INTO MM_ESTADO_FORMULARIO (ID_ESTADO, NOMBRE) VALUES (SEQ_MM_ESTADO_FORMULARIO.NEXTVAL, 'En Proceso');
INSERT INTO MM_ESTADO_FORMULARIO (ID_ESTADO, NOMBRE) VALUES (SEQ_MM_ESTADO_FORMULARIO.NEXTVAL, 'Completada');
INSERT INTO MM_ESTADO_FORMULARIO (ID_ESTADO, NOMBRE) VALUES (SEQ_MM_ESTADO_FORMULARIO.NEXTVAL, 'Cancelada');

INSERT INTO MM_TIPO_MEET (ID_TIPO_MEET, NOMBRE) VALUES (SEQ_MM_TIPO_MEET.NEXTVAL, 'Reunión de Trabajo');
INSERT INTO MM_TIPO_MEET (ID_TIPO_MEET, NOMBRE) VALUES (SEQ_MM_TIPO_MEET.NEXTVAL, 'Presentación');
INSERT INTO MM_TIPO_MEET (ID_TIPO_MEET, NOMBRE) VALUES (SEQ_MM_TIPO_MEET.NEXTVAL, 'Capacitación');
INSERT INTO MM_TIPO_MEET (ID_TIPO_MEET, NOMBRE) VALUES (SEQ_MM_TIPO_MEET.NEXTVAL, 'Revisión de Proyecto');

-- Crear índices para mejorar el rendimiento
CREATE INDEX IDX_MM_MEET_FECHA_INICIO ON MM_MEET(FECHA_INICIO);
CREATE INDEX IDX_MM_MEET_ID_SALA ON MM_MEET(ID_SALA);
CREATE INDEX IDX_MM_MEET_ID_ESTADO ON MM_MEET(ID_ESTADO);
CREATE INDEX IDX_MM_MEET_TOKEN_QR ON MM_MEET(TOKEN_QR);

-- Crear constraints de integridad referencial
ALTER TABLE MM_MEET ADD CONSTRAINT FK_MM_MEET_SALA 
    FOREIGN KEY (ID_SALA) REFERENCES MM_SALA(ID_SALA);

ALTER TABLE MM_MEET ADD CONSTRAINT FK_MM_MEET_PRIORIDAD 
    FOREIGN KEY (ID_PRIORIDAD) REFERENCES MM_PRIORIDAD(ID_PRIORIDAD);

ALTER TABLE MM_MEET ADD CONSTRAINT FK_MM_MEET_ESTADO 
    FOREIGN KEY (ID_ESTADO) REFERENCES MM_ESTADO_FORMULARIO(ID_ESTADO);

ALTER TABLE MM_MEET ADD CONSTRAINT FK_MM_MEET_TIPO 
    FOREIGN KEY (ID_TIPO_MEET) REFERENCES MM_TIPO_MEET(ID_TIPO_MEET);

-- Crear trigger para actualizar fecha de modificación
CREATE OR REPLACE TRIGGER TRG_MM_MEET_UPDATE
    BEFORE UPDATE ON MM_MEET
    FOR EACH ROW
BEGIN
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- Crear trigger para validar fechas
CREATE OR REPLACE TRIGGER TRG_MM_MEET_VALIDATE_DATES
    BEFORE INSERT OR UPDATE ON MM_MEET
    FOR EACH ROW
BEGIN
    -- Validar que la fecha de fin no sea anterior a la fecha de inicio
    IF :NEW.FECHA_FIN IS NOT NULL AND :NEW.FECHA_FIN < :NEW.FECHA_INICIO THEN
        RAISE_APPLICATION_ERROR(-20001, 'La fecha de fin no puede ser anterior a la fecha de inicio');
    END IF;
    
    -- Validar que la hora de fin no sea anterior a la hora de inicio
    IF :NEW.HORA_FIN IS NOT NULL AND :NEW.HORA_INICIO IS NOT NULL 
       AND :NEW.HORA_FIN <= :NEW.HORA_INICIO THEN
        RAISE_APPLICATION_ERROR(-20002, 'La hora de fin debe ser posterior a la hora de inicio');
    END IF;
END;
/

COMMIT;

-- =====================================================
-- VERIFICACIÓN DE CREACIÓN
-- =====================================================

-- Verificar que las tablas se crearon correctamente
SELECT table_name FROM user_tables WHERE table_name LIKE 'MM_%' ORDER BY table_name;

-- Verificar que las secuencias se crearon correctamente
SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_MM_%' ORDER BY sequence_name;

-- Verificar datos de catálogos
SELECT 'SALAS' as catalogo, COUNT(*) as total FROM MM_SALA
UNION ALL
SELECT 'PRIORIDADES' as catalogo, COUNT(*) as total FROM MM_PRIORIDAD
UNION ALL
SELECT 'ESTADOS' as catalogo, COUNT(*) as total FROM MM_ESTADO_FORMULARIO
UNION ALL
SELECT 'TIPOS_MEET' as catalogo, COUNT(*) as total FROM MM_TIPO_MEET;

